version: '3.8'
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: kpaz_db
      MYSQL_USER: kpaz
      MYSQL_PASSWORD: kpaz123
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_USER: kpaz
      DB_PASSWORD: kpaz123
      DB_NAME: kpaz_db
      PORT: 3001
      NODE_ENV: development
    ports:
      - "3001:3001"
    volumes:
      - .:/app
    command: npm run dev

volumes:
  db_data: 